# Setup
title: Лескова 29
tagline: Сайт нашего дома
url:
paginate: 1
baseurl: ""

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options


# Specify the author for blog posts
author:
  name: lskor
  url: https://twitter.com/WebGlory
  email: glory.web@gmail.com

# Custom vars
version: 3.0.0
